// src/i18n/locales/index.ts
//
// GENERATED by scripts/gen-locales-index.js — do not edit by hand.
// One JSON file per namespace per language: ./<lang>/<namespace>.json.
// English is the source of truth.

import en_auth from './en/auth.json';
import en_common from './en/common.json';
import en_create from './en/create.json';
import en_discussion from './en/discussion.json';
import en_list from './en/list.json';
import en_notifications from './en/notifications.json';
import en_share from './en/share.json';
import en_voting from './en/voting.json';

export const NAMESPACES = ['auth', 'common', 'create', 'discussion', 'list', 'notifications', 'share', 'voting'] as const;

export const resources = {
  'en': { auth: en_auth, common: en_common, create: en_create, discussion: en_discussion, list: en_list, notifications: en_notifications, share: en_share, voting: en_voting },
};
